# pFedMoAP model configuration file

MODEL:
  NAME: 'pfedmoap'
  N_CTX: 16
  D_CTX: 1
  CTX_INIT: ""
  DEPTH: 0
  PFL: true  # Personalized FL

TRAINER:
  PFEDMOAP:
    N_CTX: 16  # Number of context vectors
    CSC: false  # Class-specific context
    CTX_INIT: false  # Initialization words
    PREC: "fp16"  # Precision setting
    CLASS_TOKEN_POSITION: "end"  # Class token position
    GATING_HEADS: 8  # Number of heads in gating network
    N: 1
    GATING_EMBED_DIM: 128  # Embedding dimension in gating network
    LMBDA: 0.5  # Regularization parameter
    SCALING: 10  # Scaling of distance matrix

# pFedMoAP specific optimizer configuration
OPTIM_PFEDMOAP:
  NAME: "sgd"
  LR: 0.003
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  LR_SCHEDULER: "cosine"
  MAX_EPOCH: 1000
