# PromptFL model configuration file

MODEL:
  NAME: 'promptfl'
  N_CTX: 16
  D_CTX: 1
  CTX_INIT: ""
  DEPTH: 0

TRAINER:
  PROMPTFL:
    N_CTX: 16  # Number of context vectors
    CSC: false  # Class-specific context
    CTX_INIT: false  # Initialization words
    PREC: "fp16"  # Precision setting
    CLASS_TOKEN_POSITION: "end"  # Class token position
    N: 1  # Number of prompts
